# Generated by Django 5.0.3 on 2024-03-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='number_visits',
            field=models.IntegerField(default=0),
        ),
    ]
