# Generated by Django 5.0.3 on 2024-03-28 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl_app', '0002_alter_statistics_number_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='id_short',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorturl_app.shorturl', unique=True),
        ),
    ]
