# Generated by Django 5.0.3 on 2024-03-28 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl_app', '0004_alter_statistics_id_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='id_short',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorturl_app.shorturl'),
        ),
    ]
